#!/bin/bash

set -eu

# It seems that in conky the execi command will start before curl has completely
# written the file. For some reason adding a sleep before calling curl fixes it.
sleep 2

forecast=~/".cache/forecast.json"
weather=~/".cache/weather.json"

api_prefix="api.openweathermap.org/data/2.5/"

appid="APPID=6970b6f2f52d08a85e50f4cbaebecb85"
id="&id=3530597"
units="&units=metric"
lang="" ; [[ -v 4 ]] && lang="${4%%_*}" lang="&lang=$lang"

curl -s "${api_prefix}forecast?${appid}${id}${units}${lang}" -o "$forecast"
curl -s "${api_prefix}weather?${appid}${id}${units}${lang}" -o "$weather"
